module.exports = {
  docSidebar: {
    Spreadsheet: [
      "introduction",
      "license",
      "formula",
      "formatting",
      "konva",
      "roadmap",
    ],
    "Getting Started": ["install", "options"],
    Features: [
      "features/initialize",
      "features/sheets",
      "features/custom_formatting",
      "features/tabstrip",
      "features/statusbar",
      "features/gridlines",
      "features/cell-renderer",
      "features/borders",
      "features/fonts",
      "features/undo-redo",
      "features/selection",
      "features/context-menu",
      "features/scroll",
      "features/ui-customizations",
      "features/data-validation",
      "features/datatypes",
      "features/tooltips",
      "features/hidden-rows-columns",
    ],
    Examples: [
      "sizing",
      "freezing",
      "merging",
      "styles",
      "editor",
      "conditional_formatting",
      "range_selection",
      "autofilter",
      "excel",
      "csv",
    ],
    Advanced: ["ref", "state-reducer"],
  },
};
